# Generated by Django 4.1.1 on 2022-09-26 18:54

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_alter_controllerimage_description_and_more'), ('core', '0003_controller_name_alter_controllerimage_description_and_more'), ('core', '0004_controller_hidden'), ('core', '0005_controllerimage_primary_modimage_primary_and_more'), ('core', '0006_mod_slug')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gcc', 'OEM GameCube Controller'), ('phobgcc', 'PhobGCC'), ('rectangle', 'Rectangle')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mods', models.ManyToManyField(to='core.mod')),
                ('name', models.CharField(default='', max_length=50)),
                ('hidden', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControllerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=core.models.image_upload_path)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.controller')),
                ('primary', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=core.models.image_upload_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=core.models.image_upload_path)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.mod')),
                ('primary', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
