# Generated by Django 4.1.1 on 2022-09-24 07:02

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gcc', 'OEM GameCube Controller'), ('phobgcc', 'PhobGCC'), ('rectangle', 'Rectangle')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=core.models.image_upload_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='ModImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=core.models.image_upload_path)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.mod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControllerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=core.models.image_upload_path)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.controller')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='controller',
            name='mods',
            field=models.ManyToManyField(to='core.mod'),
        ),
    ]
