# Generated by Django 4.1.1 on 2022-09-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllerimage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='modimage',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
