# Generated by Django 4.1.1 on 2022-09-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_controller_name_alter_controllerimage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
