# Generated by Django 4.1.1 on 2022-09-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_controller_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllerimage',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modimage',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='controllerimage',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modimage',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
