# Generated by Django 4.1.1 on 2022-09-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_controllerimage_primary_modimage_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
