# Generated by Django 4.1.1 on 2022-09-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0006_mod_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mod',
            name='slug',
            field=models.SlugField(),
        ),
    ]
