# Generated by Django 4.1.1 on 2022-09-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_controller_name_alter_mod_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='display_nav',
            field=models.BooleanField(default=True),
        ),
    ]
