# Generated by Django 4.1.1 on 2022-09-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mod_display_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
