# Generated by Django 4.1.1 on 2022-09-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_controller_mods'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
