# Generated by Django 4.1.1 on 2023-04-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_controller_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='display_tier',
            field=models.IntegerField(default=100),
        ),
    ]
